version: 2
updates:
  # Backend
  - package-ecosystem: "pip"
    directory: "/backend"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1 
    labels:
      - "backend"
      - "security"
    groups:
      python-all:
        patterns:
          - "*" 

  # Frontend
  - package-ecosystem: "npm"
    directory: "/frontend"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1 
    labels:
      - "frontend"
      - "security"
    groups:
      node-all:
        patterns:
          - "*"

  # Docker-images
  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    labels:
      - "docker"
      - "security"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    labels:
      - "ci/cd"